import { GraphData } from './types';

export const mockData: GraphData = {
  nodes: [
    { id: '1', name: 'Ana García', roles: ['docente'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/ana/200', phone: '+34 600 000 001', email: 'ana.garcia@campus.edu' },
    { id: '2', name: 'Carlos Ruiz', roles: ['docente'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/carlos/200', phone: '+34 600 000 002', email: 'carlos.ruiz@campus.edu' },
    { id: '3', name: 'Elena Martínez', roles: ['padre', 'docente'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/elena/200', phone: '+34 600 000 003', email: 'elena.martinez@campus.edu' },
    { id: '4', name: 'Javier López', roles: ['padre'], photo: 'https://picsum.photos/seed/javier/200', phone: '+34 600 000 004' },
    { id: '5', name: 'Sofía López', roles: ['alumno'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/sofia/200' },
    { id: '6', name: 'Mateo López', roles: ['alumno'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/mateo/200' },
    { id: '7', name: 'Lucía Fernández', roles: ['padre'], photo: 'https://picsum.photos/seed/lucia/200', phone: '+34 600 000 007' },
    { id: '8', name: 'Diego Fernández', roles: ['alumno'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/diego/200' },
    { id: '9', name: 'Marta Sánchez', roles: ['docente'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/marta/200', phone: '+34 600 000 009', email: 'marta.sanchez@campus.edu' },
    { id: '10', name: 'Pablo Gómez', roles: ['padre'], photo: 'https://picsum.photos/seed/pablo/200', phone: '+34 600 000 010' },
    { id: '11', name: 'Sara Gómez', roles: ['alumno'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/sara/200' },
    { id: '12', name: 'Roberto Díaz', roles: ['padre'], photo: 'https://picsum.photos/seed/roberto/200', phone: '+34 600 000 012' },
    { id: '13', name: 'Hugo Díaz', roles: ['alumno'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/hugo/200' },
    { id: '14', name: 'Carmen Vega', roles: ['docente'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/carmen/200', phone: '+34 600 000 014', email: 'carmen.vega@campus.edu' },
    { id: '15', name: 'Luis Torres', roles: ['padre'], photo: 'https://picsum.photos/seed/luis/200', phone: '+34 600 000 015' },
    { id: '16', name: 'Valeria Torres', roles: ['alumno'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/valeria/200' },
    { id: '17', name: 'Isabel Rivas', roles: ['padre'], photo: 'https://picsum.photos/seed/isabel/200', phone: '+34 600 000 017' },
    { id: '18', name: 'Leo Rivas', roles: ['alumno'], classroom: 'Taller 1', photo: 'https://picsum.photos/seed/leo/200' },
    { id: '19', name: 'Fernando Castro', roles: ['docente'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/fernando/200', phone: '+34 600 000 019', email: 'fernando.castro@campus.edu' },
    { id: '20', name: 'Gloria Ortiz', roles: ['padre'], photo: 'https://picsum.photos/seed/gloria/200', phone: '+34 600 000 020' },
    { id: '21', name: 'Emma Ortiz', roles: ['alumno'], classroom: 'Taller 2', photo: 'https://picsum.photos/seed/emma/200' },
  ],
  links: [
    { source: '4', target: '5', type: 'padre-hijo' },
    { source: '4', target: '6', type: 'padre-hijo' },
    { source: '3', target: '5', type: 'padre-hijo' },
    { source: '3', target: '6', type: 'padre-hijo' },
    { source: '1', target: '5', type: 'docente-alumno' },
    { source: '1', target: '8', type: 'docente-alumno' },
    { source: '2', target: '6', type: 'docente-alumno' },
    { source: '2', target: '11', type: 'docente-alumno' },
    { source: '7', target: '8', type: 'padre-hijo' },
    { source: '10', target: '11', type: 'padre-hijo' },
    { source: '12', target: '13', type: 'padre-hijo' },
    { source: '9', target: '13', type: 'docente-alumno' },
    { source: '14', target: '16', type: 'docente-alumno' },
    { source: '15', target: '16', type: 'padre-hijo' },
    { source: '17', target: '18', type: 'padre-hijo' },
    { source: '19', target: '18', type: 'docente-alumno' },
    { source: '20', target: '21', type: 'padre-hijo' },
    { source: '1', target: '21', type: 'docente-alumno' },
    { source: '1', target: '3', type: 'padre-docente' },
    { source: '2', target: '7', type: 'padre-docente' },
    { source: '9', target: '10', type: 'padre-docente' },
    { source: '14', target: '15', type: 'padre-docente' },
    { source: '19', target: '17', type: 'padre-docente' },
  ]
};
